### ISSUE TITLE
Error: command 'githubbuild.listBuilds' not found

### ISSUE THREAD

**Issue by gencer** [grzegorzjudas/vscode-gitbuild#5]
I get `command 'githubbuild.listBuilds' not found` error.

Using VSCode 1.25.1

**Comment by grzegorzjudas** [comment]
Can you please try reinstalling the plugin? The command should have been installed along the plugin - if it's not found, it's possible something went wrong during installation.

**Comment by gencer** [comment]
@grzegorzjudas Unfortunately even fresh VSCode does not work:

![image](https://user-images.githubusercontent.com/1711576/43215787-cbf07ee6-9045-11e8-80d3-0cdfe6085c0b.png)

When I click on `Build` button I get this error. Meanwhile, I awaited up to 5 minutes but there is no build icons on my IDE.

**Comment by grzegorzjudas** [comment]
Success, failure or pending would only show up when the correct state is fetched from github (connection is made). Until then, and in case there're no builds for a commit, "-" is displayed. Can you please try opening the VSCode dev console and see if there're any errors?

I'll try investigating on my side as well.

**Comment by gencer** [comment]
```[Extension Host] Here is the error stack:  Error: ENOENT: no such file or directory, open 'C:\Program Files\Microsoft VS Code\config'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at Git.getConfigFromFile (C:\Users\gence\.vscode\extensions\grzegorzjudas.vscode-gitbuild-1.0.1\src\class\Git.ts:155:24)
    at new Git (C:\Users\gence\.vscode\extensions\grzegorzjudas.vscode-gitbuild-1.0.1\src\class\Git.ts:30:41)
    at new GitBuildPlugin (C:\Users\gence\.vscode\extensions\grzegorzjudas.vscode-gitbuild-1.0.1\src\class\Plugin.ts:27:20)
    at activate (C:\Users\gence\.vscode\extensions\grzegorzjudas.vscode-gitbuild-1.0.1\src\extension.ts:5:20)
    at Function.t._callActivateOptional (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:791:650)
    at Function.t._callActivate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:791:329)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:790:391
    at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:729)
    at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:81:61)
    at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:866)
    at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:307)
    at c (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:85:785)
    at $.then.o.(anonymous function) (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:85:999)
    at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:729)
    at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:81:61)
    at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:866)
    at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:307)
    at c (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:85:785)
    at $.then.o.(anonymous function) (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:85:999)
    at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:729)
    at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:81:61)
    at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:866)
    at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:307)
    at e.resolveOk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:554:1000)
    at e._receiveReply (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:657:394)
    at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:656:693)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:655:544
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:673
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:599
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:97:917)
    at u (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:159:721)
    at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:159:898)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3148 Activating extension 'grzegorzjudas.vscode-gitbuild' failed: ENOENT: no such file or directory, open 'C:\Program Files\Microsoft VS Code\config'.
```

**Comment by gencer** [comment]
I've found the issues:

1. You used `'/'` for folder separator. Use `path.sep` instead.
2. There is no such `https://github.com/api/v3/repos...` as api url on GitHub. It is `https://api.github.com/repos...`

Even if I fix those issues, I still get errors about `map`. Probably this extension is vay too old and can't handle existing api endpoints.

**Comment by grzegorzjudas** [comment]
Good find! I hadn't thought about Windows to be honest, so I appreciate the time you took for debugging. I'll fix the issue soon.
